### ISSUE TITLE
Support for arrays

### ISSUE THREAD

**Issue by grogy** [milo/hydrator#1]
Will be nice when the library support arrays - for example this code:

``` php
class Family
{
    /** @var string[] */
    public $imagesPath;
}
```

Examples are in [phpDocumentor](https://www.phpdoc.org/docs/latest/guides/types.html#arrays).

What do you thing about it?

**Comment by milo** [comment]
One dimension arrays should work. For which data it does not?

**Comment by grogy** [comment]
I am sorry, it is my mistake - problem is not with arrays. It works ok.

My problem is with constructor.. I will open new issues (for better documentation questions about project).
